// Code generated by "go generate"; DO NOT EDIT.
//
// Generated at: 2018-12-09 22:29:03 +0000

package brickcolor

import "image/color"

var (
	White                = BrickColor{Hex: "#F2F3F3", Number: 1, RGBA: color.RGBA{242, 243, 243, 255}, Name: "White"}
	Grey                 = BrickColor{Hex: "#A1A5A2", Number: 2, RGBA: color.RGBA{161, 165, 162, 255}, Name: "Grey"}
	LightYellow          = BrickColor{Hex: "#F9E999", Number: 3, RGBA: color.RGBA{249, 233, 153, 255}, Name: "Light yellow"}
	BrickYellow          = BrickColor{Hex: "#D7C59A", Number: 5, RGBA: color.RGBA{215, 197, 154, 255}, Name: "Brick yellow"}
	LightGreenMint       = BrickColor{Hex: "#C2DAB8", Number: 6, RGBA: color.RGBA{194, 218, 184, 255}, Name: "Light green (Mint)"}
	LightReddishViolet   = BrickColor{Hex: "#E8BAC8", Number: 9, RGBA: color.RGBA{232, 186, 200, 255}, Name: "Light reddish violet"}
	PastelBlue           = BrickColor{Hex: "#80BBDB", Number: 11, RGBA: color.RGBA{128, 187, 219, 255}, Name: "Pastel Blue"}
	LightOrangeBrown     = BrickColor{Hex: "#CB8442", Number: 12, RGBA: color.RGBA{203, 132, 66, 255}, Name: "Light orange brown"}
	Nougat               = BrickColor{Hex: "#CC8E69", Number: 18, RGBA: color.RGBA{204, 142, 105, 255}, Name: "Nougat"}
	BrightRed            = BrickColor{Hex: "#C4281C", Number: 21, RGBA: color.RGBA{196, 40, 28, 255}, Name: "Bright red"}
	MedReddishViolet     = BrickColor{Hex: "#C470A0", Number: 22, RGBA: color.RGBA{196, 112, 160, 255}, Name: "Med. reddish violet"}
	BrightBlue           = BrickColor{Hex: "#0D69AC", Number: 23, RGBA: color.RGBA{13, 105, 172, 255}, Name: "Bright blue"}
	BrightYellow         = BrickColor{Hex: "#F5CD30", Number: 24, RGBA: color.RGBA{245, 205, 48, 255}, Name: "Bright yellow"}
	EarthOrange          = BrickColor{Hex: "#624732", Number: 25, RGBA: color.RGBA{98, 71, 50, 255}, Name: "Earth orange"}
	Black                = BrickColor{Hex: "#1B2A35", Number: 26, RGBA: color.RGBA{27, 42, 53, 255}, Name: "Black"}
	DarkGrey             = BrickColor{Hex: "#6D6E6C", Number: 27, RGBA: color.RGBA{109, 110, 108, 255}, Name: "Dark grey"}
	DarkGreen            = BrickColor{Hex: "#287F47", Number: 28, RGBA: color.RGBA{40, 127, 71, 255}, Name: "Dark green"}
	MediumGreen          = BrickColor{Hex: "#A1C48C", Number: 29, RGBA: color.RGBA{161, 196, 140, 255}, Name: "Medium green"}
	LigYellowichOrange   = BrickColor{Hex: "#F3CF9B", Number: 36, RGBA: color.RGBA{243, 207, 155, 255}, Name: "Lig. Yellowich orange"}
	BrightGreen          = BrickColor{Hex: "#4B974B", Number: 37, RGBA: color.RGBA{75, 151, 75, 255}, Name: "Bright green"}
	DarkOrange           = BrickColor{Hex: "#A05F35", Number: 38, RGBA: color.RGBA{160, 95, 53, 255}, Name: "Dark orange"}
	LightBluishViolet    = BrickColor{Hex: "#C1CADE", Number: 39, RGBA: color.RGBA{193, 202, 222, 255}, Name: "Light bluish violet"}
	Transparent          = BrickColor{Hex: "#ECECEC", Number: 40, RGBA: color.RGBA{236, 236, 236, 255}, Name: "Transparent"}
	TrRed                = BrickColor{Hex: "#CD544B", Number: 41, RGBA: color.RGBA{205, 84, 75, 255}, Name: "Tr. Red"}
	TrLgBlue             = BrickColor{Hex: "#C1DFF0", Number: 42, RGBA: color.RGBA{193, 223, 240, 255}, Name: "Tr. Lg blue"}
	TrBlue               = BrickColor{Hex: "#7BB6E8", Number: 43, RGBA: color.RGBA{123, 182, 232, 255}, Name: "Tr. Blue"}
	TrYellow             = BrickColor{Hex: "#F7F18D", Number: 44, RGBA: color.RGBA{247, 241, 141, 255}, Name: "Tr. Yellow"}
	LightBlue            = BrickColor{Hex: "#B4D2E4", Number: 45, RGBA: color.RGBA{180, 210, 228, 255}, Name: "Light blue"}
	TrFluReddishOrange   = BrickColor{Hex: "#D9856C", Number: 47, RGBA: color.RGBA{217, 133, 108, 255}, Name: "Tr. Flu. Reddish orange"}
	TrGreen              = BrickColor{Hex: "#84B68D", Number: 48, RGBA: color.RGBA{132, 182, 141, 255}, Name: "Tr. Green"}
	TrFluGreen           = BrickColor{Hex: "#F8F184", Number: 49, RGBA: color.RGBA{248, 241, 132, 255}, Name: "Tr. Flu. Green"}
	PhosphWhite          = BrickColor{Hex: "#ECE8DE", Number: 50, RGBA: color.RGBA{236, 232, 222, 255}, Name: "Phosph. White"}
	LightRed             = BrickColor{Hex: "#EEC4B6", Number: 100, RGBA: color.RGBA{238, 196, 182, 255}, Name: "Light red"}
	MediumRed            = BrickColor{Hex: "#DA867A", Number: 101, RGBA: color.RGBA{218, 134, 122, 255}, Name: "Medium red"}
	MediumBlue           = BrickColor{Hex: "#6E99CA", Number: 102, RGBA: color.RGBA{110, 153, 202, 255}, Name: "Medium blue"}
	LightGrey            = BrickColor{Hex: "#C7C1B7", Number: 103, RGBA: color.RGBA{199, 193, 183, 255}, Name: "Light grey"}
	BrightViolet         = BrickColor{Hex: "#6B327C", Number: 104, RGBA: color.RGBA{107, 50, 124, 255}, Name: "Bright violet"}
	BrYellowishOrange    = BrickColor{Hex: "#E29B40", Number: 105, RGBA: color.RGBA{226, 155, 64, 255}, Name: "Br. yellowish orange"}
	BrightOrange         = BrickColor{Hex: "#DA8541", Number: 106, RGBA: color.RGBA{218, 133, 65, 255}, Name: "Bright orange"}
	BrightBluishGreen    = BrickColor{Hex: "#008F9C", Number: 107, RGBA: color.RGBA{0, 143, 156, 255}, Name: "Bright bluish green"}
	EarthYellow          = BrickColor{Hex: "#685C43", Number: 108, RGBA: color.RGBA{104, 92, 67, 255}, Name: "Earth yellow"}
	BrightBluishViolet   = BrickColor{Hex: "#435493", Number: 110, RGBA: color.RGBA{67, 84, 147, 255}, Name: "Bright bluish violet"}
	TrBrown              = BrickColor{Hex: "#BFB7B1", Number: 111, RGBA: color.RGBA{191, 183, 177, 255}, Name: "Tr. Brown"}
	MediumBluishViolet   = BrickColor{Hex: "#6874AC", Number: 112, RGBA: color.RGBA{104, 116, 172, 255}, Name: "Medium bluish violet"}
	TrMediReddishViolet  = BrickColor{Hex: "#E5ADC8", Number: 113, RGBA: color.RGBA{229, 173, 200, 255}, Name: "Tr. Medi. reddish violet"}
	MedYellowishGreen    = BrickColor{Hex: "#C7D23C", Number: 115, RGBA: color.RGBA{199, 210, 60, 255}, Name: "Med. yellowish green"}
	MedBluishGreen       = BrickColor{Hex: "#55A5AF", Number: 116, RGBA: color.RGBA{85, 165, 175, 255}, Name: "Med. bluish green"}
	LightBluishGreen     = BrickColor{Hex: "#B7D7D5", Number: 118, RGBA: color.RGBA{183, 215, 213, 255}, Name: "Light bluish green"}
	BrYellowishGreen     = BrickColor{Hex: "#A4BD47", Number: 119, RGBA: color.RGBA{164, 189, 71, 255}, Name: "Br. yellowish green"}
	LigYellowishGreen    = BrickColor{Hex: "#D9E4A7", Number: 120, RGBA: color.RGBA{217, 228, 167, 255}, Name: "Lig. yellowish green"}
	MedYellowishOrange   = BrickColor{Hex: "#E7AC58", Number: 121, RGBA: color.RGBA{231, 172, 88, 255}, Name: "Med. yellowish orange"}
	BrReddishOrange      = BrickColor{Hex: "#D36F4C", Number: 123, RGBA: color.RGBA{211, 111, 76, 255}, Name: "Br. reddish orange"}
	BrightReddishViolet  = BrickColor{Hex: "#923978", Number: 124, RGBA: color.RGBA{146, 57, 120, 255}, Name: "Bright reddish violet"}
	LightOrange          = BrickColor{Hex: "#EAB892", Number: 125, RGBA: color.RGBA{234, 184, 146, 255}, Name: "Light orange"}
	TrBrightBluishViolet = BrickColor{Hex: "#A5A5CB", Number: 126, RGBA: color.RGBA{165, 165, 203, 255}, Name: "Tr. Bright bluish violet"}
	Gold                 = BrickColor{Hex: "#DCBC81", Number: 127, RGBA: color.RGBA{220, 188, 129, 255}, Name: "Gold"}
	DarkNougat           = BrickColor{Hex: "#AE7A59", Number: 128, RGBA: color.RGBA{174, 122, 89, 255}, Name: "Dark nougat"}
	Silver               = BrickColor{Hex: "#9CA3A8", Number: 131, RGBA: color.RGBA{156, 163, 168, 255}, Name: "Silver"}
	NeonOrange           = BrickColor{Hex: "#D5733D", Number: 133, RGBA: color.RGBA{213, 115, 61, 255}, Name: "Neon orange"}
	NeonGreen            = BrickColor{Hex: "#D8DD56", Number: 134, RGBA: color.RGBA{216, 221, 86, 255}, Name: "Neon green"}
	SandBlue             = BrickColor{Hex: "#74869D", Number: 135, RGBA: color.RGBA{116, 134, 157, 255}, Name: "Sand blue"}
	SandViolet           = BrickColor{Hex: "#877C90", Number: 136, RGBA: color.RGBA{135, 124, 144, 255}, Name: "Sand violet"}
	MediumOrange         = BrickColor{Hex: "#E09864", Number: 137, RGBA: color.RGBA{224, 152, 100, 255}, Name: "Medium orange"}
	SandYellow           = BrickColor{Hex: "#958A73", Number: 138, RGBA: color.RGBA{149, 138, 115, 255}, Name: "Sand yellow"}
	EarthBlue            = BrickColor{Hex: "#203A56", Number: 140, RGBA: color.RGBA{32, 58, 86, 255}, Name: "Earth blue"}
	EarthGreen           = BrickColor{Hex: "#27462D", Number: 141, RGBA: color.RGBA{39, 70, 45, 255}, Name: "Earth green"}
	TrFluBlue            = BrickColor{Hex: "#CFE2F7", Number: 143, RGBA: color.RGBA{207, 226, 247, 255}, Name: "Tr. Flu. Blue"}
	SandBlueMetallic     = BrickColor{Hex: "#7988A1", Number: 145, RGBA: color.RGBA{121, 136, 161, 255}, Name: "Sand blue metallic"}
	SandVioletMetallic   = BrickColor{Hex: "#958EA3", Number: 146, RGBA: color.RGBA{149, 142, 163, 255}, Name: "Sand violet metallic"}
	SandYellowMetallic   = BrickColor{Hex: "#938767", Number: 147, RGBA: color.RGBA{147, 135, 103, 255}, Name: "Sand yellow metallic"}
	DarkGreyMetallic     = BrickColor{Hex: "#575857", Number: 148, RGBA: color.RGBA{87, 88, 87, 255}, Name: "Dark grey metallic"}
	BlackMetallic        = BrickColor{Hex: "#161D32", Number: 149, RGBA: color.RGBA{22, 29, 50, 255}, Name: "Black metallic"}
	LightGreyMetallic    = BrickColor{Hex: "#ABADAC", Number: 150, RGBA: color.RGBA{171, 173, 172, 255}, Name: "Light grey metallic"}
	SandGreen            = BrickColor{Hex: "#789082", Number: 151, RGBA: color.RGBA{120, 144, 130, 255}, Name: "Sand green"}
	SandRed              = BrickColor{Hex: "#957977", Number: 153, RGBA: color.RGBA{149, 121, 119, 255}, Name: "Sand red"}
	DarkRed              = BrickColor{Hex: "#7B2E2F", Number: 154, RGBA: color.RGBA{123, 46, 47, 255}, Name: "Dark red"}
	TrFluYellow          = BrickColor{Hex: "#FFF67B", Number: 157, RGBA: color.RGBA{255, 246, 123, 255}, Name: "Tr. Flu. Yellow"}
	TrFluRed             = BrickColor{Hex: "#E1A4C2", Number: 158, RGBA: color.RGBA{225, 164, 194, 255}, Name: "Tr. Flu. Red"}
	GunMetallic          = BrickColor{Hex: "#756C62", Number: 168, RGBA: color.RGBA{117, 108, 98, 255}, Name: "Gun metallic"}
	RedFlipFlop          = BrickColor{Hex: "#97695B", Number: 176, RGBA: color.RGBA{151, 105, 91, 255}, Name: "Red flip/flop"}
	YellowFlipFlop       = BrickColor{Hex: "#B48455", Number: 178, RGBA: color.RGBA{180, 132, 85, 255}, Name: "Yellow flip/flop"}
	SilverFlipFlop       = BrickColor{Hex: "#898788", Number: 179, RGBA: color.RGBA{137, 135, 136, 255}, Name: "Silver flip/flop"}
	Curry                = BrickColor{Hex: "#D7A94B", Number: 180, RGBA: color.RGBA{215, 169, 75, 255}, Name: "Curry"}
	FireYellow           = BrickColor{Hex: "#F9D62E", Number: 190, RGBA: color.RGBA{249, 214, 46, 255}, Name: "Fire Yellow"}
	FlameYellowishOrange = BrickColor{Hex: "#E8AB2D", Number: 191, RGBA: color.RGBA{232, 171, 45, 255}, Name: "Flame yellowish orange"}
	ReddishBrown         = BrickColor{Hex: "#694028", Number: 192, RGBA: color.RGBA{105, 64, 40, 255}, Name: "Reddish brown"}
	FlameReddishOrange   = BrickColor{Hex: "#CF6024", Number: 193, RGBA: color.RGBA{207, 96, 36, 255}, Name: "Flame reddish orange"}
	MediumStoneGrey      = BrickColor{Hex: "#A3A2A5", Number: 194, RGBA: color.RGBA{163, 162, 165, 255}, Name: "Medium stone grey"}
	RoyalBlue            = BrickColor{Hex: "#4667A4", Number: 195, RGBA: color.RGBA{70, 103, 164, 255}, Name: "Royal blue"}
	DarkRoyalBlue        = BrickColor{Hex: "#23478B", Number: 196, RGBA: color.RGBA{35, 71, 139, 255}, Name: "Dark Royal blue"}
	BrightReddishLilac   = BrickColor{Hex: "#8E4285", Number: 198, RGBA: color.RGBA{142, 66, 133, 255}, Name: "Bright reddish lilac"}
	DarkStoneGrey        = BrickColor{Hex: "#635F62", Number: 199, RGBA: color.RGBA{99, 95, 98, 255}, Name: "Dark stone grey"}
	LemonMetalic         = BrickColor{Hex: "#828A5D", Number: 200, RGBA: color.RGBA{130, 138, 93, 255}, Name: "Lemon metalic"}
	LightStoneGrey       = BrickColor{Hex: "#E5E4DF", Number: 208, RGBA: color.RGBA{229, 228, 223, 255}, Name: "Light stone grey"}
	DarkCurry            = BrickColor{Hex: "#B08E44", Number: 209, RGBA: color.RGBA{176, 142, 68, 255}, Name: "Dark Curry"}
	FadedGreen           = BrickColor{Hex: "#709578", Number: 210, RGBA: color.RGBA{112, 149, 120, 255}, Name: "Faded green"}
	Turquoise            = BrickColor{Hex: "#79B5B5", Number: 211, RGBA: color.RGBA{121, 181, 181, 255}, Name: "Turquoise"}
	LightRoyalBlue       = BrickColor{Hex: "#9FC3E9", Number: 212, RGBA: color.RGBA{159, 195, 233, 255}, Name: "Light Royal blue"}
	MediumRoyalBlue      = BrickColor{Hex: "#6C81B7", Number: 213, RGBA: color.RGBA{108, 129, 183, 255}, Name: "Medium Royal blue"}
	Rust                 = BrickColor{Hex: "#904C2A", Number: 216, RGBA: color.RGBA{144, 76, 42, 255}, Name: "Rust"}
	Brown                = BrickColor{Hex: "#7C5C46", Number: 217, RGBA: color.RGBA{124, 92, 70, 255}, Name: "Brown"}
	ReddishLilac         = BrickColor{Hex: "#96709F", Number: 218, RGBA: color.RGBA{150, 112, 159, 255}, Name: "Reddish lilac"}
	Lilac                = BrickColor{Hex: "#6B629B", Number: 219, RGBA: color.RGBA{107, 98, 155, 255}, Name: "Lilac"}
	LightLilac           = BrickColor{Hex: "#A7A9CE", Number: 220, RGBA: color.RGBA{167, 169, 206, 255}, Name: "Light lilac"}
	BrightPurple         = BrickColor{Hex: "#CD6298", Number: 221, RGBA: color.RGBA{205, 98, 152, 255}, Name: "Bright purple"}
	LightPurple          = BrickColor{Hex: "#E4ADC8", Number: 222, RGBA: color.RGBA{228, 173, 200, 255}, Name: "Light purple"}
	LightPink            = BrickColor{Hex: "#DC9095", Number: 223, RGBA: color.RGBA{220, 144, 149, 255}, Name: "Light pink"}
	LightBrickYellow     = BrickColor{Hex: "#F0D5A0", Number: 224, RGBA: color.RGBA{240, 213, 160, 255}, Name: "Light brick yellow"}
	WarmYellowishOrange  = BrickColor{Hex: "#EBB87F", Number: 225, RGBA: color.RGBA{235, 184, 127, 255}, Name: "Warm yellowish orange"}
	CoolYellow           = BrickColor{Hex: "#FDEA8D", Number: 226, RGBA: color.RGBA{253, 234, 141, 255}, Name: "Cool yellow"}
	DoveBlue             = BrickColor{Hex: "#7DBBDD", Number: 232, RGBA: color.RGBA{125, 187, 221, 255}, Name: "Dove blue"}
	MediumLilac          = BrickColor{Hex: "#342B75", Number: 268, RGBA: color.RGBA{52, 43, 117, 255}, Name: "Medium lilac"}
	SlimeGreen           = BrickColor{Hex: "#506D54", Number: 301, RGBA: color.RGBA{80, 109, 84, 255}, Name: "Slime green"}
	SmokyGrey            = BrickColor{Hex: "#5B5D69", Number: 302, RGBA: color.RGBA{91, 93, 105, 255}, Name: "Smoky grey"}
	DarkBlue             = BrickColor{Hex: "#0010B0", Number: 303, RGBA: color.RGBA{0, 16, 176, 255}, Name: "Dark blue"}
	ParsleyGreen         = BrickColor{Hex: "#2C651D", Number: 304, RGBA: color.RGBA{44, 101, 29, 255}, Name: "Parsley green"}
	SteelBlue            = BrickColor{Hex: "#527CAE", Number: 305, RGBA: color.RGBA{82, 124, 174, 255}, Name: "Steel blue"}
	StormBlue            = BrickColor{Hex: "#335882", Number: 306, RGBA: color.RGBA{51, 88, 130, 255}, Name: "Storm blue"}
	Lapis                = BrickColor{Hex: "#102ADC", Number: 307, RGBA: color.RGBA{16, 42, 220, 255}, Name: "Lapis"}
	DarkIndigo           = BrickColor{Hex: "#3D1585", Number: 308, RGBA: color.RGBA{61, 21, 133, 255}, Name: "Dark indigo"}
	SeaGreen             = BrickColor{Hex: "#348E40", Number: 309, RGBA: color.RGBA{52, 142, 64, 255}, Name: "Sea green"}
	Shamrock             = BrickColor{Hex: "#5B9A4C", Number: 310, RGBA: color.RGBA{91, 154, 76, 255}, Name: "Shamrock"}
	Fossil               = BrickColor{Hex: "#9FA1AC", Number: 311, RGBA: color.RGBA{159, 161, 172, 255}, Name: "Fossil"}
	Mulberry             = BrickColor{Hex: "#592259", Number: 312, RGBA: color.RGBA{89, 34, 89, 255}, Name: "Mulberry"}
	ForestGreen          = BrickColor{Hex: "#1F801D", Number: 313, RGBA: color.RGBA{31, 128, 29, 255}, Name: "Forest green"}
	CadetBlue            = BrickColor{Hex: "#9FADC0", Number: 314, RGBA: color.RGBA{159, 173, 192, 255}, Name: "Cadet blue"}
	ElectricBlue         = BrickColor{Hex: "#0989CF", Number: 315, RGBA: color.RGBA{9, 137, 207, 255}, Name: "Electric blue"}
	Eggplant             = BrickColor{Hex: "#7B007B", Number: 316, RGBA: color.RGBA{123, 0, 123, 255}, Name: "Eggplant"}
	Moss                 = BrickColor{Hex: "#7C9C6B", Number: 317, RGBA: color.RGBA{124, 156, 107, 255}, Name: "Moss"}
	Artichoke            = BrickColor{Hex: "#8AAB85", Number: 318, RGBA: color.RGBA{138, 171, 133, 255}, Name: "Artichoke"}
	SageGreen            = BrickColor{Hex: "#B9C4B1", Number: 319, RGBA: color.RGBA{185, 196, 177, 255}, Name: "Sage green"}
	GhostGrey            = BrickColor{Hex: "#CACBD1", Number: 320, RGBA: color.RGBA{202, 203, 209, 255}, Name: "Ghost grey"}
	Lilac2               = BrickColor{Hex: "#A75E9B", Number: 321, RGBA: color.RGBA{167, 94, 155, 255}, Name: "Lilac"}
	Plum                 = BrickColor{Hex: "#7B2F7B", Number: 322, RGBA: color.RGBA{123, 47, 123, 255}, Name: "Plum"}
	Olivine              = BrickColor{Hex: "#94BE81", Number: 323, RGBA: color.RGBA{148, 190, 129, 255}, Name: "Olivine"}
	LaurelGreen          = BrickColor{Hex: "#A8BD99", Number: 324, RGBA: color.RGBA{168, 189, 153, 255}, Name: "Laurel green"}
	QuillGrey            = BrickColor{Hex: "#DFDFDE", Number: 325, RGBA: color.RGBA{223, 223, 222, 255}, Name: "Quill grey"}
	Crimson              = BrickColor{Hex: "#970000", Number: 327, RGBA: color.RGBA{151, 0, 0, 255}, Name: "Crimson"}
	Mint                 = BrickColor{Hex: "#B1E5A6", Number: 328, RGBA: color.RGBA{177, 229, 166, 255}, Name: "Mint"}
	BabyBlue             = BrickColor{Hex: "#98C2DB", Number: 329, RGBA: color.RGBA{152, 194, 219, 255}, Name: "Baby blue"}
	CarnationPink        = BrickColor{Hex: "#FF98DC", Number: 330, RGBA: color.RGBA{255, 152, 220, 255}, Name: "Carnation pink"}
	Persimmon            = BrickColor{Hex: "#FF5959", Number: 331, RGBA: color.RGBA{255, 89, 89, 255}, Name: "Persimmon"}
	Maroon               = BrickColor{Hex: "#750000", Number: 332, RGBA: color.RGBA{117, 0, 0, 255}, Name: "Maroon"}
	Gold2                = BrickColor{Hex: "#EFB838", Number: 333, RGBA: color.RGBA{239, 184, 56, 255}, Name: "Gold"}
	DaisyOrange          = BrickColor{Hex: "#F8D96D", Number: 334, RGBA: color.RGBA{248, 217, 109, 255}, Name: "Daisy orange"}
	Pearl                = BrickColor{Hex: "#E7E7EC", Number: 335, RGBA: color.RGBA{231, 231, 236, 255}, Name: "Pearl"}
	Fog                  = BrickColor{Hex: "#C7D4E4", Number: 336, RGBA: color.RGBA{199, 212, 228, 255}, Name: "Fog"}
	Salmon               = BrickColor{Hex: "#FF9494", Number: 337, RGBA: color.RGBA{255, 148, 148, 255}, Name: "Salmon"}
	TerraCotta           = BrickColor{Hex: "#BE6862", Number: 338, RGBA: color.RGBA{190, 104, 98, 255}, Name: "Terra Cotta"}
	Cocoa                = BrickColor{Hex: "#562424", Number: 339, RGBA: color.RGBA{86, 36, 36, 255}, Name: "Cocoa"}
	Wheat                = BrickColor{Hex: "#F1E7C7", Number: 340, RGBA: color.RGBA{241, 231, 199, 255}, Name: "Wheat"}
	Buttermilk           = BrickColor{Hex: "#FEF3BB", Number: 341, RGBA: color.RGBA{254, 243, 187, 255}, Name: "Buttermilk"}
	Mauve                = BrickColor{Hex: "#E0B2D0", Number: 342, RGBA: color.RGBA{224, 178, 208, 255}, Name: "Mauve"}
	Sunrise              = BrickColor{Hex: "#D490BD", Number: 343, RGBA: color.RGBA{212, 144, 189, 255}, Name: "Sunrise"}
	Tawny                = BrickColor{Hex: "#965555", Number: 344, RGBA: color.RGBA{150, 85, 85, 255}, Name: "Tawny"}
	Rust2                = BrickColor{Hex: "#8F4C2A", Number: 345, RGBA: color.RGBA{143, 76, 42, 255}, Name: "Rust"}
	Cashmere             = BrickColor{Hex: "#D3BE96", Number: 346, RGBA: color.RGBA{211, 190, 150, 255}, Name: "Cashmere"}
	Khaki                = BrickColor{Hex: "#E2DCBC", Number: 347, RGBA: color.RGBA{226, 220, 188, 255}, Name: "Khaki"}
	LilyWhite            = BrickColor{Hex: "#EDEAEA", Number: 348, RGBA: color.RGBA{237, 234, 234, 255}, Name: "Lily white"}
	Seashell             = BrickColor{Hex: "#E9DADA", Number: 349, RGBA: color.RGBA{233, 218, 218, 255}, Name: "Seashell"}
	Burgundy             = BrickColor{Hex: "#883E3E", Number: 350, RGBA: color.RGBA{136, 62, 62, 255}, Name: "Burgundy"}
	Cork                 = BrickColor{Hex: "#BC9B5D", Number: 351, RGBA: color.RGBA{188, 155, 93, 255}, Name: "Cork"}
	Burlap               = BrickColor{Hex: "#C7AC78", Number: 352, RGBA: color.RGBA{199, 172, 120, 255}, Name: "Burlap"}
	Beige                = BrickColor{Hex: "#CABFA3", Number: 353, RGBA: color.RGBA{202, 191, 163, 255}, Name: "Beige"}
	Oyster               = BrickColor{Hex: "#BBB3B2", Number: 354, RGBA: color.RGBA{187, 179, 178, 255}, Name: "Oyster"}
	PineCone             = BrickColor{Hex: "#6C584B", Number: 355, RGBA: color.RGBA{108, 88, 75, 255}, Name: "Pine Cone"}
	FawnBrown            = BrickColor{Hex: "#A0844F", Number: 356, RGBA: color.RGBA{160, 132, 79, 255}, Name: "Fawn brown"}
	HurricaneGrey        = BrickColor{Hex: "#958988", Number: 357, RGBA: color.RGBA{149, 137, 136, 255}, Name: "Hurricane grey"}
	CloudyGrey           = BrickColor{Hex: "#ABA89E", Number: 358, RGBA: color.RGBA{171, 168, 158, 255}, Name: "Cloudy grey"}
	Linen                = BrickColor{Hex: "#AF9483", Number: 359, RGBA: color.RGBA{175, 148, 131, 255}, Name: "Linen"}
	Copper               = BrickColor{Hex: "#966766", Number: 360, RGBA: color.RGBA{150, 103, 102, 255}, Name: "Copper"}
	DirtBrown            = BrickColor{Hex: "#564236", Number: 361, RGBA: color.RGBA{86, 66, 54, 255}, Name: "Dirt brown"}
	Bronze               = BrickColor{Hex: "#7E683F", Number: 362, RGBA: color.RGBA{126, 104, 63, 255}, Name: "Bronze"}
	Flint                = BrickColor{Hex: "#69665C", Number: 363, RGBA: color.RGBA{105, 102, 92, 255}, Name: "Flint"}
	DarkTaupe            = BrickColor{Hex: "#5A4C42", Number: 364, RGBA: color.RGBA{90, 76, 66, 255}, Name: "Dark taupe"}
	BurntSienna          = BrickColor{Hex: "#6A3909", Number: 365, RGBA: color.RGBA{106, 57, 9, 255}, Name: "Burnt Sienna"}
	InstitutionalWhite   = BrickColor{Hex: "#F8F8F8", Number: 1001, RGBA: color.RGBA{248, 248, 248, 255}, Name: "Institutional white"}
	MidGray              = BrickColor{Hex: "#CDCDCD", Number: 1002, RGBA: color.RGBA{205, 205, 205, 255}, Name: "Mid gray"}
	ReallyBlack          = BrickColor{Hex: "#111111", Number: 1003, RGBA: color.RGBA{17, 17, 17, 255}, Name: "Really black"}
	ReallyRed            = BrickColor{Hex: "#FF0000", Number: 1004, RGBA: color.RGBA{255, 0, 0, 255}, Name: "Really red"}
	DeepOrange           = BrickColor{Hex: "#FFB000", Number: 1005, RGBA: color.RGBA{255, 176, 0, 255}, Name: "Deep orange"}
	Alder                = BrickColor{Hex: "#B480FF", Number: 1006, RGBA: color.RGBA{180, 128, 255, 255}, Name: "Alder"}
	DustyRose            = BrickColor{Hex: "#A34B4B", Number: 1007, RGBA: color.RGBA{163, 75, 75, 255}, Name: "Dusty Rose"}
	Olive                = BrickColor{Hex: "#C1BE42", Number: 1008, RGBA: color.RGBA{193, 190, 66, 255}, Name: "Olive"}
	NewYeller            = BrickColor{Hex: "#FFFF00", Number: 1009, RGBA: color.RGBA{255, 255, 0, 255}, Name: "New Yeller"}
	ReallyBlue           = BrickColor{Hex: "#0000FF", Number: 1010, RGBA: color.RGBA{0, 0, 255, 255}, Name: "Really blue"}
	NavyBlue             = BrickColor{Hex: "#002060", Number: 1011, RGBA: color.RGBA{0, 32, 96, 255}, Name: "Navy blue"}
	DeepBlue             = BrickColor{Hex: "#2154B9", Number: 1012, RGBA: color.RGBA{33, 84, 185, 255}, Name: "Deep blue"}
	Cyan                 = BrickColor{Hex: "#04AFEC", Number: 1013, RGBA: color.RGBA{4, 175, 236, 255}, Name: "Cyan"}
	CGABrown             = BrickColor{Hex: "#AA5500", Number: 1014, RGBA: color.RGBA{170, 85, 0, 255}, Name: "CGA brown"}
	Magenta              = BrickColor{Hex: "#AA00AA", Number: 1015, RGBA: color.RGBA{170, 0, 170, 255}, Name: "Magenta"}
	Pink                 = BrickColor{Hex: "#FF66CC", Number: 1016, RGBA: color.RGBA{255, 102, 204, 255}, Name: "Pink"}
	DeepOrange2          = BrickColor{Hex: "#FFAF00", Number: 1017, RGBA: color.RGBA{255, 175, 0, 255}, Name: "Deep orange"}
	Teal                 = BrickColor{Hex: "#12EED4", Number: 1018, RGBA: color.RGBA{18, 238, 212, 255}, Name: "Teal"}
	Toothpaste           = BrickColor{Hex: "#00FFFF", Number: 1019, RGBA: color.RGBA{0, 255, 255, 255}, Name: "Toothpaste"}
	LimeGreen            = BrickColor{Hex: "#00FF00", Number: 1020, RGBA: color.RGBA{0, 255, 0, 255}, Name: "Lime green"}
	Camo                 = BrickColor{Hex: "#3A7D15", Number: 1021, RGBA: color.RGBA{58, 125, 21, 255}, Name: "Camo"}
	Grime                = BrickColor{Hex: "#7F8E64", Number: 1022, RGBA: color.RGBA{127, 142, 100, 255}, Name: "Grime"}
	Lavender             = BrickColor{Hex: "#8C5B9F", Number: 1023, RGBA: color.RGBA{140, 91, 159, 255}, Name: "Lavender"}
	PastelLightBlue      = BrickColor{Hex: "#AFDDFF", Number: 1024, RGBA: color.RGBA{175, 221, 255, 255}, Name: "Pastel light blue"}
	PastelOrange         = BrickColor{Hex: "#FFC9C9", Number: 1025, RGBA: color.RGBA{255, 201, 201, 255}, Name: "Pastel orange"}
	PastelViolet         = BrickColor{Hex: "#B1A7FF", Number: 1026, RGBA: color.RGBA{177, 167, 255, 255}, Name: "Pastel violet"}
	PastelBlueGreen      = BrickColor{Hex: "#9FF3E9", Number: 1027, RGBA: color.RGBA{159, 243, 233, 255}, Name: "Pastel blue-green"}
	PastelGreen          = BrickColor{Hex: "#CCFFCC", Number: 1028, RGBA: color.RGBA{204, 255, 204, 255}, Name: "Pastel green"}
	PastelYellow         = BrickColor{Hex: "#FFFFCC", Number: 1029, RGBA: color.RGBA{255, 255, 204, 255}, Name: "Pastel yellow"}
	PastelBrown          = BrickColor{Hex: "#FFCC99", Number: 1030, RGBA: color.RGBA{255, 204, 153, 255}, Name: "Pastel brown"}
	RoyalPurple          = BrickColor{Hex: "#6225D1", Number: 1031, RGBA: color.RGBA{98, 37, 209, 255}, Name: "Royal purple"}
	HotPink              = BrickColor{Hex: "#FF00BF", Number: 1032, RGBA: color.RGBA{255, 0, 191, 255}, Name: "Hot pink"}
)

// All available BrickColors on Roblox.
var All = []BrickColor{
	White,
	Grey,
	LightYellow,
	BrickYellow,
	LightGreenMint,
	LightReddishViolet,
	PastelBlue,
	LightOrangeBrown,
	Nougat,
	BrightRed,
	MedReddishViolet,
	BrightBlue,
	BrightYellow,
	EarthOrange,
	Black,
	DarkGrey,
	DarkGreen,
	MediumGreen,
	LigYellowichOrange,
	BrightGreen,
	DarkOrange,
	LightBluishViolet,
	Transparent,
	TrRed,
	TrLgBlue,
	TrBlue,
	TrYellow,
	LightBlue,
	TrFluReddishOrange,
	TrGreen,
	TrFluGreen,
	PhosphWhite,
	LightRed,
	MediumRed,
	MediumBlue,
	LightGrey,
	BrightViolet,
	BrYellowishOrange,
	BrightOrange,
	BrightBluishGreen,
	EarthYellow,
	BrightBluishViolet,
	TrBrown,
	MediumBluishViolet,
	TrMediReddishViolet,
	MedYellowishGreen,
	MedBluishGreen,
	LightBluishGreen,
	BrYellowishGreen,
	LigYellowishGreen,
	MedYellowishOrange,
	BrReddishOrange,
	BrightReddishViolet,
	LightOrange,
	TrBrightBluishViolet,
	Gold,
	DarkNougat,
	Silver,
	NeonOrange,
	NeonGreen,
	SandBlue,
	SandViolet,
	MediumOrange,
	SandYellow,
	EarthBlue,
	EarthGreen,
	TrFluBlue,
	SandBlueMetallic,
	SandVioletMetallic,
	SandYellowMetallic,
	DarkGreyMetallic,
	BlackMetallic,
	LightGreyMetallic,
	SandGreen,
	SandRed,
	DarkRed,
	TrFluYellow,
	TrFluRed,
	GunMetallic,
	RedFlipFlop,
	YellowFlipFlop,
	SilverFlipFlop,
	Curry,
	FireYellow,
	FlameYellowishOrange,
	ReddishBrown,
	FlameReddishOrange,
	MediumStoneGrey,
	RoyalBlue,
	DarkRoyalBlue,
	BrightReddishLilac,
	DarkStoneGrey,
	LemonMetalic,
	LightStoneGrey,
	DarkCurry,
	FadedGreen,
	Turquoise,
	LightRoyalBlue,
	MediumRoyalBlue,
	Rust,
	Brown,
	ReddishLilac,
	Lilac,
	LightLilac,
	BrightPurple,
	LightPurple,
	LightPink,
	LightBrickYellow,
	WarmYellowishOrange,
	CoolYellow,
	DoveBlue,
	MediumLilac,
	SlimeGreen,
	SmokyGrey,
	DarkBlue,
	ParsleyGreen,
	SteelBlue,
	StormBlue,
	Lapis,
	DarkIndigo,
	SeaGreen,
	Shamrock,
	Fossil,
	Mulberry,
	ForestGreen,
	CadetBlue,
	ElectricBlue,
	Eggplant,
	Moss,
	Artichoke,
	SageGreen,
	GhostGrey,
	Lilac2,
	Plum,
	Olivine,
	LaurelGreen,
	QuillGrey,
	Crimson,
	Mint,
	BabyBlue,
	CarnationPink,
	Persimmon,
	Maroon,
	Gold2,
	DaisyOrange,
	Pearl,
	Fog,
	Salmon,
	TerraCotta,
	Cocoa,
	Wheat,
	Buttermilk,
	Mauve,
	Sunrise,
	Tawny,
	Rust2,
	Cashmere,
	Khaki,
	LilyWhite,
	Seashell,
	Burgundy,
	Cork,
	Burlap,
	Beige,
	Oyster,
	PineCone,
	FawnBrown,
	HurricaneGrey,
	CloudyGrey,
	Linen,
	Copper,
	DirtBrown,
	Bronze,
	Flint,
	DarkTaupe,
	BurntSienna,
	InstitutionalWhite,
	MidGray,
	ReallyBlack,
	ReallyRed,
	DeepOrange,
	Alder,
	DustyRose,
	Olive,
	NewYeller,
	ReallyBlue,
	NavyBlue,
	DeepBlue,
	Cyan,
	CGABrown,
	Magenta,
	Pink,
	DeepOrange2,
	Teal,
	Toothpaste,
	LimeGreen,
	Camo,
	Grime,
	Lavender,
	PastelLightBlue,
	PastelOrange,
	PastelViolet,
	PastelBlueGreen,
	PastelGreen,
	PastelYellow,
	PastelBrown,
	RoyalPurple,
	HotPink}

var byNumber = map[int]BrickColor{
	1:    White,
	2:    Grey,
	3:    LightYellow,
	5:    BrickYellow,
	6:    LightGreenMint,
	9:    LightReddishViolet,
	11:   PastelBlue,
	12:   LightOrangeBrown,
	18:   Nougat,
	21:   BrightRed,
	22:   MedReddishViolet,
	23:   BrightBlue,
	24:   BrightYellow,
	25:   EarthOrange,
	26:   Black,
	27:   DarkGrey,
	28:   DarkGreen,
	29:   MediumGreen,
	36:   LigYellowichOrange,
	37:   BrightGreen,
	38:   DarkOrange,
	39:   LightBluishViolet,
	40:   Transparent,
	41:   TrRed,
	42:   TrLgBlue,
	43:   TrBlue,
	44:   TrYellow,
	45:   LightBlue,
	47:   TrFluReddishOrange,
	48:   TrGreen,
	49:   TrFluGreen,
	50:   PhosphWhite,
	100:  LightRed,
	101:  MediumRed,
	102:  MediumBlue,
	103:  LightGrey,
	104:  BrightViolet,
	105:  BrYellowishOrange,
	106:  BrightOrange,
	107:  BrightBluishGreen,
	108:  EarthYellow,
	110:  BrightBluishViolet,
	111:  TrBrown,
	112:  MediumBluishViolet,
	113:  TrMediReddishViolet,
	115:  MedYellowishGreen,
	116:  MedBluishGreen,
	118:  LightBluishGreen,
	119:  BrYellowishGreen,
	120:  LigYellowishGreen,
	121:  MedYellowishOrange,
	123:  BrReddishOrange,
	124:  BrightReddishViolet,
	125:  LightOrange,
	126:  TrBrightBluishViolet,
	127:  Gold,
	128:  DarkNougat,
	131:  Silver,
	133:  NeonOrange,
	134:  NeonGreen,
	135:  SandBlue,
	136:  SandViolet,
	137:  MediumOrange,
	138:  SandYellow,
	140:  EarthBlue,
	141:  EarthGreen,
	143:  TrFluBlue,
	145:  SandBlueMetallic,
	146:  SandVioletMetallic,
	147:  SandYellowMetallic,
	148:  DarkGreyMetallic,
	149:  BlackMetallic,
	150:  LightGreyMetallic,
	151:  SandGreen,
	153:  SandRed,
	154:  DarkRed,
	157:  TrFluYellow,
	158:  TrFluRed,
	168:  GunMetallic,
	176:  RedFlipFlop,
	178:  YellowFlipFlop,
	179:  SilverFlipFlop,
	180:  Curry,
	190:  FireYellow,
	191:  FlameYellowishOrange,
	192:  ReddishBrown,
	193:  FlameReddishOrange,
	194:  MediumStoneGrey,
	195:  RoyalBlue,
	196:  DarkRoyalBlue,
	198:  BrightReddishLilac,
	199:  DarkStoneGrey,
	200:  LemonMetalic,
	208:  LightStoneGrey,
	209:  DarkCurry,
	210:  FadedGreen,
	211:  Turquoise,
	212:  LightRoyalBlue,
	213:  MediumRoyalBlue,
	216:  Rust,
	217:  Brown,
	218:  ReddishLilac,
	219:  Lilac,
	220:  LightLilac,
	221:  BrightPurple,
	222:  LightPurple,
	223:  LightPink,
	224:  LightBrickYellow,
	225:  WarmYellowishOrange,
	226:  CoolYellow,
	232:  DoveBlue,
	268:  MediumLilac,
	301:  SlimeGreen,
	302:  SmokyGrey,
	303:  DarkBlue,
	304:  ParsleyGreen,
	305:  SteelBlue,
	306:  StormBlue,
	307:  Lapis,
	308:  DarkIndigo,
	309:  SeaGreen,
	310:  Shamrock,
	311:  Fossil,
	312:  Mulberry,
	313:  ForestGreen,
	314:  CadetBlue,
	315:  ElectricBlue,
	316:  Eggplant,
	317:  Moss,
	318:  Artichoke,
	319:  SageGreen,
	320:  GhostGrey,
	321:  Lilac2,
	322:  Plum,
	323:  Olivine,
	324:  LaurelGreen,
	325:  QuillGrey,
	327:  Crimson,
	328:  Mint,
	329:  BabyBlue,
	330:  CarnationPink,
	331:  Persimmon,
	332:  Maroon,
	333:  Gold2,
	334:  DaisyOrange,
	335:  Pearl,
	336:  Fog,
	337:  Salmon,
	338:  TerraCotta,
	339:  Cocoa,
	340:  Wheat,
	341:  Buttermilk,
	342:  Mauve,
	343:  Sunrise,
	344:  Tawny,
	345:  Rust2,
	346:  Cashmere,
	347:  Khaki,
	348:  LilyWhite,
	349:  Seashell,
	350:  Burgundy,
	351:  Cork,
	352:  Burlap,
	353:  Beige,
	354:  Oyster,
	355:  PineCone,
	356:  FawnBrown,
	357:  HurricaneGrey,
	358:  CloudyGrey,
	359:  Linen,
	360:  Copper,
	361:  DirtBrown,
	362:  Bronze,
	363:  Flint,
	364:  DarkTaupe,
	365:  BurntSienna,
	1001: InstitutionalWhite,
	1002: MidGray,
	1003: ReallyBlack,
	1004: ReallyRed,
	1005: DeepOrange,
	1006: Alder,
	1007: DustyRose,
	1008: Olive,
	1009: NewYeller,
	1010: ReallyBlue,
	1011: NavyBlue,
	1012: DeepBlue,
	1013: Cyan,
	1014: CGABrown,
	1015: Magenta,
	1016: Pink,
	1017: DeepOrange2,
	1018: Teal,
	1019: Toothpaste,
	1020: LimeGreen,
	1021: Camo,
	1022: Grime,
	1023: Lavender,
	1024: PastelLightBlue,
	1025: PastelOrange,
	1026: PastelViolet,
	1027: PastelBlueGreen,
	1028: PastelGreen,
	1029: PastelYellow,
	1030: PastelBrown,
	1031: RoyalPurple,
	1032: HotPink,
}
