// Code generated by "go generate"; DO NOT EDIT.
//
// Generated at: 2018-12-09 22:21:22 +0000

package brickcolor

import "image/color"

var (
	White                = BrickColor{Name: "White", Number: 1, Hex: "#F2F3F3", RGBA: color.RGBA{242, 243, 243, 255}}
	Grey                 = BrickColor{Name: "Grey", Number: 2, Hex: "#A1A5A2", RGBA: color.RGBA{161, 165, 162, 255}}
	LightYellow          = BrickColor{Name: "Light yellow", Number: 3, Hex: "#F9E999", RGBA: color.RGBA{249, 233, 153, 255}}
	BrickYellow          = BrickColor{Name: "Brick yellow", Number: 5, Hex: "#D7C59A", RGBA: color.RGBA{215, 197, 154, 255}}
	LightGreenMint       = BrickColor{Name: "Light green (Mint)", Number: 6, Hex: "#C2DAB8", RGBA: color.RGBA{194, 218, 184, 255}}
	LightReddishViolet   = BrickColor{Name: "Light reddish violet", Number: 9, Hex: "#E8BAC8", RGBA: color.RGBA{232, 186, 200, 255}}
	PastelBlue           = BrickColor{Name: "Pastel Blue", Number: 11, Hex: "#80BBDB", RGBA: color.RGBA{128, 187, 219, 255}}
	LightOrangeBrown     = BrickColor{Name: "Light orange brown", Number: 12, Hex: "#CB8442", RGBA: color.RGBA{203, 132, 66, 255}}
	Nougat               = BrickColor{Name: "Nougat", Number: 18, Hex: "#CC8E69", RGBA: color.RGBA{204, 142, 105, 255}}
	BrightRed            = BrickColor{Name: "Bright red", Number: 21, Hex: "#C4281C", RGBA: color.RGBA{196, 40, 28, 255}}
	MedReddishViolet     = BrickColor{Name: "Med. reddish violet", Number: 22, Hex: "#C470A0", RGBA: color.RGBA{196, 112, 160, 255}}
	BrightBlue           = BrickColor{Name: "Bright blue", Number: 23, Hex: "#0D69AC", RGBA: color.RGBA{13, 105, 172, 255}}
	BrightYellow         = BrickColor{Name: "Bright yellow", Number: 24, Hex: "#F5CD30", RGBA: color.RGBA{245, 205, 48, 255}}
	EarthOrange          = BrickColor{Name: "Earth orange", Number: 25, Hex: "#624732", RGBA: color.RGBA{98, 71, 50, 255}}
	Black                = BrickColor{Name: "Black", Number: 26, Hex: "#1B2A35", RGBA: color.RGBA{27, 42, 53, 255}}
	DarkGrey             = BrickColor{Name: "Dark grey", Number: 27, Hex: "#6D6E6C", RGBA: color.RGBA{109, 110, 108, 255}}
	DarkGreen            = BrickColor{Name: "Dark green", Number: 28, Hex: "#287F47", RGBA: color.RGBA{40, 127, 71, 255}}
	MediumGreen          = BrickColor{Name: "Medium green", Number: 29, Hex: "#A1C48C", RGBA: color.RGBA{161, 196, 140, 255}}
	LigYellowichOrange   = BrickColor{Name: "Lig. Yellowich orange", Number: 36, Hex: "#F3CF9B", RGBA: color.RGBA{243, 207, 155, 255}}
	BrightGreen          = BrickColor{Name: "Bright green", Number: 37, Hex: "#4B974B", RGBA: color.RGBA{75, 151, 75, 255}}
	DarkOrange           = BrickColor{Name: "Dark orange", Number: 38, Hex: "#A05F35", RGBA: color.RGBA{160, 95, 53, 255}}
	LightBluishViolet    = BrickColor{Name: "Light bluish violet", Number: 39, Hex: "#C1CADE", RGBA: color.RGBA{193, 202, 222, 255}}
	Transparent          = BrickColor{Name: "Transparent", Number: 40, Hex: "#ECECEC", RGBA: color.RGBA{236, 236, 236, 255}}
	TrRed                = BrickColor{Name: "Tr. Red", Number: 41, Hex: "#CD544B", RGBA: color.RGBA{205, 84, 75, 255}}
	TrLgBlue             = BrickColor{Name: "Tr. Lg blue", Number: 42, Hex: "#C1DFF0", RGBA: color.RGBA{193, 223, 240, 255}}
	TrBlue               = BrickColor{Name: "Tr. Blue", Number: 43, Hex: "#7BB6E8", RGBA: color.RGBA{123, 182, 232, 255}}
	TrYellow             = BrickColor{Name: "Tr. Yellow", Number: 44, Hex: "#F7F18D", RGBA: color.RGBA{247, 241, 141, 255}}
	LightBlue            = BrickColor{Name: "Light blue", Number: 45, Hex: "#B4D2E4", RGBA: color.RGBA{180, 210, 228, 255}}
	TrFluReddishOrange   = BrickColor{Name: "Tr. Flu. Reddish orange", Number: 47, Hex: "#D9856C", RGBA: color.RGBA{217, 133, 108, 255}}
	TrGreen              = BrickColor{Name: "Tr. Green", Number: 48, Hex: "#84B68D", RGBA: color.RGBA{132, 182, 141, 255}}
	TrFluGreen           = BrickColor{Name: "Tr. Flu. Green", Number: 49, Hex: "#F8F184", RGBA: color.RGBA{248, 241, 132, 255}}
	PhosphWhite          = BrickColor{Name: "Phosph. White", Number: 50, Hex: "#ECE8DE", RGBA: color.RGBA{236, 232, 222, 255}}
	LightRed             = BrickColor{Name: "Light red", Number: 100, Hex: "#EEC4B6", RGBA: color.RGBA{238, 196, 182, 255}}
	MediumRed            = BrickColor{Name: "Medium red", Number: 101, Hex: "#DA867A", RGBA: color.RGBA{218, 134, 122, 255}}
	MediumBlue           = BrickColor{Name: "Medium blue", Number: 102, Hex: "#6E99CA", RGBA: color.RGBA{110, 153, 202, 255}}
	LightGrey            = BrickColor{Name: "Light grey", Number: 103, Hex: "#C7C1B7", RGBA: color.RGBA{199, 193, 183, 255}}
	BrightViolet         = BrickColor{Name: "Bright violet", Number: 104, Hex: "#6B327C", RGBA: color.RGBA{107, 50, 124, 255}}
	BrYellowishOrange    = BrickColor{Name: "Br. yellowish orange", Number: 105, Hex: "#E29B40", RGBA: color.RGBA{226, 155, 64, 255}}
	BrightOrange         = BrickColor{Name: "Bright orange", Number: 106, Hex: "#DA8541", RGBA: color.RGBA{218, 133, 65, 255}}
	BrightBluishGreen    = BrickColor{Name: "Bright bluish green", Number: 107, Hex: "#008F9C", RGBA: color.RGBA{0, 143, 156, 255}}
	EarthYellow          = BrickColor{Name: "Earth yellow", Number: 108, Hex: "#685C43", RGBA: color.RGBA{104, 92, 67, 255}}
	BrightBluishViolet   = BrickColor{Name: "Bright bluish violet", Number: 110, Hex: "#435493", RGBA: color.RGBA{67, 84, 147, 255}}
	TrBrown              = BrickColor{Name: "Tr. Brown", Number: 111, Hex: "#BFB7B1", RGBA: color.RGBA{191, 183, 177, 255}}
	MediumBluishViolet   = BrickColor{Name: "Medium bluish violet", Number: 112, Hex: "#6874AC", RGBA: color.RGBA{104, 116, 172, 255}}
	TrMediReddishViolet  = BrickColor{Name: "Tr. Medi. reddish violet", Number: 113, Hex: "#E5ADC8", RGBA: color.RGBA{229, 173, 200, 255}}
	MedYellowishGreen    = BrickColor{Name: "Med. yellowish green", Number: 115, Hex: "#C7D23C", RGBA: color.RGBA{199, 210, 60, 255}}
	MedBluishGreen       = BrickColor{Name: "Med. bluish green", Number: 116, Hex: "#55A5AF", RGBA: color.RGBA{85, 165, 175, 255}}
	LightBluishGreen     = BrickColor{Name: "Light bluish green", Number: 118, Hex: "#B7D7D5", RGBA: color.RGBA{183, 215, 213, 255}}
	BrYellowishGreen     = BrickColor{Name: "Br. yellowish green", Number: 119, Hex: "#A4BD47", RGBA: color.RGBA{164, 189, 71, 255}}
	LigYellowishGreen    = BrickColor{Name: "Lig. yellowish green", Number: 120, Hex: "#D9E4A7", RGBA: color.RGBA{217, 228, 167, 255}}
	MedYellowishOrange   = BrickColor{Name: "Med. yellowish orange", Number: 121, Hex: "#E7AC58", RGBA: color.RGBA{231, 172, 88, 255}}
	BrReddishOrange      = BrickColor{Name: "Br. reddish orange", Number: 123, Hex: "#D36F4C", RGBA: color.RGBA{211, 111, 76, 255}}
	BrightReddishViolet  = BrickColor{Name: "Bright reddish violet", Number: 124, Hex: "#923978", RGBA: color.RGBA{146, 57, 120, 255}}
	LightOrange          = BrickColor{Name: "Light orange", Number: 125, Hex: "#EAB892", RGBA: color.RGBA{234, 184, 146, 255}}
	TrBrightBluishViolet = BrickColor{Name: "Tr. Bright bluish violet", Number: 126, Hex: "#A5A5CB", RGBA: color.RGBA{165, 165, 203, 255}}
	Gold                 = BrickColor{Name: "Gold", Number: 127, Hex: "#DCBC81", RGBA: color.RGBA{220, 188, 129, 255}}
	DarkNougat           = BrickColor{Name: "Dark nougat", Number: 128, Hex: "#AE7A59", RGBA: color.RGBA{174, 122, 89, 255}}
	Silver               = BrickColor{Name: "Silver", Number: 131, Hex: "#9CA3A8", RGBA: color.RGBA{156, 163, 168, 255}}
	NeonOrange           = BrickColor{Name: "Neon orange", Number: 133, Hex: "#D5733D", RGBA: color.RGBA{213, 115, 61, 255}}
	NeonGreen            = BrickColor{Name: "Neon green", Number: 134, Hex: "#D8DD56", RGBA: color.RGBA{216, 221, 86, 255}}
	SandBlue             = BrickColor{Name: "Sand blue", Number: 135, Hex: "#74869D", RGBA: color.RGBA{116, 134, 157, 255}}
	SandViolet           = BrickColor{Name: "Sand violet", Number: 136, Hex: "#877C90", RGBA: color.RGBA{135, 124, 144, 255}}
	MediumOrange         = BrickColor{Name: "Medium orange", Number: 137, Hex: "#E09864", RGBA: color.RGBA{224, 152, 100, 255}}
	SandYellow           = BrickColor{Name: "Sand yellow", Number: 138, Hex: "#958A73", RGBA: color.RGBA{149, 138, 115, 255}}
	EarthBlue            = BrickColor{Name: "Earth blue", Number: 140, Hex: "#203A56", RGBA: color.RGBA{32, 58, 86, 255}}
	EarthGreen           = BrickColor{Name: "Earth green", Number: 141, Hex: "#27462D", RGBA: color.RGBA{39, 70, 45, 255}}
	TrFluBlue            = BrickColor{Name: "Tr. Flu. Blue", Number: 143, Hex: "#CFE2F7", RGBA: color.RGBA{207, 226, 247, 255}}
	SandBlueMetallic     = BrickColor{Name: "Sand blue metallic", Number: 145, Hex: "#7988A1", RGBA: color.RGBA{121, 136, 161, 255}}
	SandVioletMetallic   = BrickColor{Name: "Sand violet metallic", Number: 146, Hex: "#958EA3", RGBA: color.RGBA{149, 142, 163, 255}}
	SandYellowMetallic   = BrickColor{Name: "Sand yellow metallic", Number: 147, Hex: "#938767", RGBA: color.RGBA{147, 135, 103, 255}}
	DarkGreyMetallic     = BrickColor{Name: "Dark grey metallic", Number: 148, Hex: "#575857", RGBA: color.RGBA{87, 88, 87, 255}}
	BlackMetallic        = BrickColor{Name: "Black metallic", Number: 149, Hex: "#161D32", RGBA: color.RGBA{22, 29, 50, 255}}
	LightGreyMetallic    = BrickColor{Name: "Light grey metallic", Number: 150, Hex: "#ABADAC", RGBA: color.RGBA{171, 173, 172, 255}}
	SandGreen            = BrickColor{Name: "Sand green", Number: 151, Hex: "#789082", RGBA: color.RGBA{120, 144, 130, 255}}
	SandRed              = BrickColor{Name: "Sand red", Number: 153, Hex: "#957977", RGBA: color.RGBA{149, 121, 119, 255}}
	DarkRed              = BrickColor{Name: "Dark red", Number: 154, Hex: "#7B2E2F", RGBA: color.RGBA{123, 46, 47, 255}}
	TrFluYellow          = BrickColor{Name: "Tr. Flu. Yellow", Number: 157, Hex: "#FFF67B", RGBA: color.RGBA{255, 246, 123, 255}}
	TrFluRed             = BrickColor{Name: "Tr. Flu. Red", Number: 158, Hex: "#E1A4C2", RGBA: color.RGBA{225, 164, 194, 255}}
	GunMetallic          = BrickColor{Name: "Gun metallic", Number: 168, Hex: "#756C62", RGBA: color.RGBA{117, 108, 98, 255}}
	RedFlipFlop          = BrickColor{Name: "Red flip/flop", Number: 176, Hex: "#97695B", RGBA: color.RGBA{151, 105, 91, 255}}
	YellowFlipFlop       = BrickColor{Name: "Yellow flip/flop", Number: 178, Hex: "#B48455", RGBA: color.RGBA{180, 132, 85, 255}}
	SilverFlipFlop       = BrickColor{Name: "Silver flip/flop", Number: 179, Hex: "#898788", RGBA: color.RGBA{137, 135, 136, 255}}
	Curry                = BrickColor{Name: "Curry", Number: 180, Hex: "#D7A94B", RGBA: color.RGBA{215, 169, 75, 255}}
	FireYellow           = BrickColor{Name: "Fire Yellow", Number: 190, Hex: "#F9D62E", RGBA: color.RGBA{249, 214, 46, 255}}
	FlameYellowishOrange = BrickColor{Name: "Flame yellowish orange", Number: 191, Hex: "#E8AB2D", RGBA: color.RGBA{232, 171, 45, 255}}
	ReddishBrown         = BrickColor{Name: "Reddish brown", Number: 192, Hex: "#694028", RGBA: color.RGBA{105, 64, 40, 255}}
	FlameReddishOrange   = BrickColor{Name: "Flame reddish orange", Number: 193, Hex: "#CF6024", RGBA: color.RGBA{207, 96, 36, 255}}
	MediumStoneGrey      = BrickColor{Name: "Medium stone grey", Number: 194, Hex: "#A3A2A5", RGBA: color.RGBA{163, 162, 165, 255}}
	RoyalBlue            = BrickColor{Name: "Royal blue", Number: 195, Hex: "#4667A4", RGBA: color.RGBA{70, 103, 164, 255}}
	DarkRoyalBlue        = BrickColor{Name: "Dark Royal blue", Number: 196, Hex: "#23478B", RGBA: color.RGBA{35, 71, 139, 255}}
	BrightReddishLilac   = BrickColor{Name: "Bright reddish lilac", Number: 198, Hex: "#8E4285", RGBA: color.RGBA{142, 66, 133, 255}}
	DarkStoneGrey        = BrickColor{Name: "Dark stone grey", Number: 199, Hex: "#635F62", RGBA: color.RGBA{99, 95, 98, 255}}
	LemonMetalic         = BrickColor{Name: "Lemon metalic", Number: 200, Hex: "#828A5D", RGBA: color.RGBA{130, 138, 93, 255}}
	LightStoneGrey       = BrickColor{Name: "Light stone grey", Number: 208, Hex: "#E5E4DF", RGBA: color.RGBA{229, 228, 223, 255}}
	DarkCurry            = BrickColor{Name: "Dark Curry", Number: 209, Hex: "#B08E44", RGBA: color.RGBA{176, 142, 68, 255}}
	FadedGreen           = BrickColor{Name: "Faded green", Number: 210, Hex: "#709578", RGBA: color.RGBA{112, 149, 120, 255}}
	Turquoise            = BrickColor{Name: "Turquoise", Number: 211, Hex: "#79B5B5", RGBA: color.RGBA{121, 181, 181, 255}}
	LightRoyalBlue       = BrickColor{Name: "Light Royal blue", Number: 212, Hex: "#9FC3E9", RGBA: color.RGBA{159, 195, 233, 255}}
	MediumRoyalBlue      = BrickColor{Name: "Medium Royal blue", Number: 213, Hex: "#6C81B7", RGBA: color.RGBA{108, 129, 183, 255}}
	Rust                 = BrickColor{Name: "Rust", Number: 216, Hex: "#904C2A", RGBA: color.RGBA{144, 76, 42, 255}}
	Brown                = BrickColor{Name: "Brown", Number: 217, Hex: "#7C5C46", RGBA: color.RGBA{124, 92, 70, 255}}
	ReddishLilac         = BrickColor{Name: "Reddish lilac", Number: 218, Hex: "#96709F", RGBA: color.RGBA{150, 112, 159, 255}}
	Lilac                = BrickColor{Name: "Lilac", Number: 219, Hex: "#6B629B", RGBA: color.RGBA{107, 98, 155, 255}}
	LightLilac           = BrickColor{Name: "Light lilac", Number: 220, Hex: "#A7A9CE", RGBA: color.RGBA{167, 169, 206, 255}}
	BrightPurple         = BrickColor{Name: "Bright purple", Number: 221, Hex: "#CD6298", RGBA: color.RGBA{205, 98, 152, 255}}
	LightPurple          = BrickColor{Name: "Light purple", Number: 222, Hex: "#E4ADC8", RGBA: color.RGBA{228, 173, 200, 255}}
	LightPink            = BrickColor{Name: "Light pink", Number: 223, Hex: "#DC9095", RGBA: color.RGBA{220, 144, 149, 255}}
	LightBrickYellow     = BrickColor{Name: "Light brick yellow", Number: 224, Hex: "#F0D5A0", RGBA: color.RGBA{240, 213, 160, 255}}
	WarmYellowishOrange  = BrickColor{Name: "Warm yellowish orange", Number: 225, Hex: "#EBB87F", RGBA: color.RGBA{235, 184, 127, 255}}
	CoolYellow           = BrickColor{Name: "Cool yellow", Number: 226, Hex: "#FDEA8D", RGBA: color.RGBA{253, 234, 141, 255}}
	DoveBlue             = BrickColor{Name: "Dove blue", Number: 232, Hex: "#7DBBDD", RGBA: color.RGBA{125, 187, 221, 255}}
	MediumLilac          = BrickColor{Name: "Medium lilac", Number: 268, Hex: "#342B75", RGBA: color.RGBA{52, 43, 117, 255}}
	SlimeGreen           = BrickColor{Name: "Slime green", Number: 301, Hex: "#506D54", RGBA: color.RGBA{80, 109, 84, 255}}
	SmokyGrey            = BrickColor{Name: "Smoky grey", Number: 302, Hex: "#5B5D69", RGBA: color.RGBA{91, 93, 105, 255}}
	DarkBlue             = BrickColor{Name: "Dark blue", Number: 303, Hex: "#0010B0", RGBA: color.RGBA{0, 16, 176, 255}}
	ParsleyGreen         = BrickColor{Name: "Parsley green", Number: 304, Hex: "#2C651D", RGBA: color.RGBA{44, 101, 29, 255}}
	SteelBlue            = BrickColor{Name: "Steel blue", Number: 305, Hex: "#527CAE", RGBA: color.RGBA{82, 124, 174, 255}}
	StormBlue            = BrickColor{Name: "Storm blue", Number: 306, Hex: "#335882", RGBA: color.RGBA{51, 88, 130, 255}}
	Lapis                = BrickColor{Name: "Lapis", Number: 307, Hex: "#102ADC", RGBA: color.RGBA{16, 42, 220, 255}}
	DarkIndigo           = BrickColor{Name: "Dark indigo", Number: 308, Hex: "#3D1585", RGBA: color.RGBA{61, 21, 133, 255}}
	SeaGreen             = BrickColor{Name: "Sea green", Number: 309, Hex: "#348E40", RGBA: color.RGBA{52, 142, 64, 255}}
	Shamrock             = BrickColor{Name: "Shamrock", Number: 310, Hex: "#5B9A4C", RGBA: color.RGBA{91, 154, 76, 255}}
	Fossil               = BrickColor{Name: "Fossil", Number: 311, Hex: "#9FA1AC", RGBA: color.RGBA{159, 161, 172, 255}}
	Mulberry             = BrickColor{Name: "Mulberry", Number: 312, Hex: "#592259", RGBA: color.RGBA{89, 34, 89, 255}}
	ForestGreen          = BrickColor{Name: "Forest green", Number: 313, Hex: "#1F801D", RGBA: color.RGBA{31, 128, 29, 255}}
	CadetBlue            = BrickColor{Name: "Cadet blue", Number: 314, Hex: "#9FADC0", RGBA: color.RGBA{159, 173, 192, 255}}
	ElectricBlue         = BrickColor{Name: "Electric blue", Number: 315, Hex: "#0989CF", RGBA: color.RGBA{9, 137, 207, 255}}
	Eggplant             = BrickColor{Name: "Eggplant", Number: 316, Hex: "#7B007B", RGBA: color.RGBA{123, 0, 123, 255}}
	Moss                 = BrickColor{Name: "Moss", Number: 317, Hex: "#7C9C6B", RGBA: color.RGBA{124, 156, 107, 255}}
	Artichoke            = BrickColor{Name: "Artichoke", Number: 318, Hex: "#8AAB85", RGBA: color.RGBA{138, 171, 133, 255}}
	SageGreen            = BrickColor{Name: "Sage green", Number: 319, Hex: "#B9C4B1", RGBA: color.RGBA{185, 196, 177, 255}}
	GhostGrey            = BrickColor{Name: "Ghost grey", Number: 320, Hex: "#CACBD1", RGBA: color.RGBA{202, 203, 209, 255}}
	Lilac2               = BrickColor{Name: "Lilac", Number: 321, Hex: "#A75E9B", RGBA: color.RGBA{167, 94, 155, 255}}
	Plum                 = BrickColor{Name: "Plum", Number: 322, Hex: "#7B2F7B", RGBA: color.RGBA{123, 47, 123, 255}}
	Olivine              = BrickColor{Name: "Olivine", Number: 323, Hex: "#94BE81", RGBA: color.RGBA{148, 190, 129, 255}}
	LaurelGreen          = BrickColor{Name: "Laurel green", Number: 324, Hex: "#A8BD99", RGBA: color.RGBA{168, 189, 153, 255}}
	QuillGrey            = BrickColor{Name: "Quill grey", Number: 325, Hex: "#DFDFDE", RGBA: color.RGBA{223, 223, 222, 255}}
	Crimson              = BrickColor{Name: "Crimson", Number: 327, Hex: "#970000", RGBA: color.RGBA{151, 0, 0, 255}}
	Mint                 = BrickColor{Name: "Mint", Number: 328, Hex: "#B1E5A6", RGBA: color.RGBA{177, 229, 166, 255}}
	BabyBlue             = BrickColor{Name: "Baby blue", Number: 329, Hex: "#98C2DB", RGBA: color.RGBA{152, 194, 219, 255}}
	CarnationPink        = BrickColor{Name: "Carnation pink", Number: 330, Hex: "#FF98DC", RGBA: color.RGBA{255, 152, 220, 255}}
	Persimmon            = BrickColor{Name: "Persimmon", Number: 331, Hex: "#FF5959", RGBA: color.RGBA{255, 89, 89, 255}}
	Maroon               = BrickColor{Name: "Maroon", Number: 332, Hex: "#750000", RGBA: color.RGBA{117, 0, 0, 255}}
	Gold2                = BrickColor{Name: "Gold", Number: 333, Hex: "#EFB838", RGBA: color.RGBA{239, 184, 56, 255}}
	DaisyOrange          = BrickColor{Name: "Daisy orange", Number: 334, Hex: "#F8D96D", RGBA: color.RGBA{248, 217, 109, 255}}
	Pearl                = BrickColor{Name: "Pearl", Number: 335, Hex: "#E7E7EC", RGBA: color.RGBA{231, 231, 236, 255}}
	Fog                  = BrickColor{Name: "Fog", Number: 336, Hex: "#C7D4E4", RGBA: color.RGBA{199, 212, 228, 255}}
	Salmon               = BrickColor{Name: "Salmon", Number: 337, Hex: "#FF9494", RGBA: color.RGBA{255, 148, 148, 255}}
	TerraCotta           = BrickColor{Name: "Terra Cotta", Number: 338, Hex: "#BE6862", RGBA: color.RGBA{190, 104, 98, 255}}
	Cocoa                = BrickColor{Name: "Cocoa", Number: 339, Hex: "#562424", RGBA: color.RGBA{86, 36, 36, 255}}
	Wheat                = BrickColor{Name: "Wheat", Number: 340, Hex: "#F1E7C7", RGBA: color.RGBA{241, 231, 199, 255}}
	Buttermilk           = BrickColor{Name: "Buttermilk", Number: 341, Hex: "#FEF3BB", RGBA: color.RGBA{254, 243, 187, 255}}
	Mauve                = BrickColor{Name: "Mauve", Number: 342, Hex: "#E0B2D0", RGBA: color.RGBA{224, 178, 208, 255}}
	Sunrise              = BrickColor{Name: "Sunrise", Number: 343, Hex: "#D490BD", RGBA: color.RGBA{212, 144, 189, 255}}
	Tawny                = BrickColor{Name: "Tawny", Number: 344, Hex: "#965555", RGBA: color.RGBA{150, 85, 85, 255}}
	Rust2                = BrickColor{Name: "Rust", Number: 345, Hex: "#8F4C2A", RGBA: color.RGBA{143, 76, 42, 255}}
	Cashmere             = BrickColor{Name: "Cashmere", Number: 346, Hex: "#D3BE96", RGBA: color.RGBA{211, 190, 150, 255}}
	Khaki                = BrickColor{Name: "Khaki", Number: 347, Hex: "#E2DCBC", RGBA: color.RGBA{226, 220, 188, 255}}
	LilyWhite            = BrickColor{Name: "Lily white", Number: 348, Hex: "#EDEAEA", RGBA: color.RGBA{237, 234, 234, 255}}
	Seashell             = BrickColor{Name: "Seashell", Number: 349, Hex: "#E9DADA", RGBA: color.RGBA{233, 218, 218, 255}}
	Burgundy             = BrickColor{Name: "Burgundy", Number: 350, Hex: "#883E3E", RGBA: color.RGBA{136, 62, 62, 255}}
	Cork                 = BrickColor{Name: "Cork", Number: 351, Hex: "#BC9B5D", RGBA: color.RGBA{188, 155, 93, 255}}
	Burlap               = BrickColor{Name: "Burlap", Number: 352, Hex: "#C7AC78", RGBA: color.RGBA{199, 172, 120, 255}}
	Beige                = BrickColor{Name: "Beige", Number: 353, Hex: "#CABFA3", RGBA: color.RGBA{202, 191, 163, 255}}
	Oyster               = BrickColor{Name: "Oyster", Number: 354, Hex: "#BBB3B2", RGBA: color.RGBA{187, 179, 178, 255}}
	PineCone             = BrickColor{Name: "Pine Cone", Number: 355, Hex: "#6C584B", RGBA: color.RGBA{108, 88, 75, 255}}
	FawnBrown            = BrickColor{Name: "Fawn brown", Number: 356, Hex: "#A0844F", RGBA: color.RGBA{160, 132, 79, 255}}
	HurricaneGrey        = BrickColor{Name: "Hurricane grey", Number: 357, Hex: "#958988", RGBA: color.RGBA{149, 137, 136, 255}}
	CloudyGrey           = BrickColor{Name: "Cloudy grey", Number: 358, Hex: "#ABA89E", RGBA: color.RGBA{171, 168, 158, 255}}
	Linen                = BrickColor{Name: "Linen", Number: 359, Hex: "#AF9483", RGBA: color.RGBA{175, 148, 131, 255}}
	Copper               = BrickColor{Name: "Copper", Number: 360, Hex: "#966766", RGBA: color.RGBA{150, 103, 102, 255}}
	DirtBrown            = BrickColor{Name: "Dirt brown", Number: 361, Hex: "#564236", RGBA: color.RGBA{86, 66, 54, 255}}
	Bronze               = BrickColor{Name: "Bronze", Number: 362, Hex: "#7E683F", RGBA: color.RGBA{126, 104, 63, 255}}
	Flint                = BrickColor{Name: "Flint", Number: 363, Hex: "#69665C", RGBA: color.RGBA{105, 102, 92, 255}}
	DarkTaupe            = BrickColor{Name: "Dark taupe", Number: 364, Hex: "#5A4C42", RGBA: color.RGBA{90, 76, 66, 255}}
	BurntSienna          = BrickColor{Name: "Burnt Sienna", Number: 365, Hex: "#6A3909", RGBA: color.RGBA{106, 57, 9, 255}}
	InstitutionalWhite   = BrickColor{Name: "Institutional white", Number: 1001, Hex: "#F8F8F8", RGBA: color.RGBA{248, 248, 248, 255}}
	MidGray              = BrickColor{Name: "Mid gray", Number: 1002, Hex: "#CDCDCD", RGBA: color.RGBA{205, 205, 205, 255}}
	ReallyBlack          = BrickColor{Name: "Really black", Number: 1003, Hex: "#111111", RGBA: color.RGBA{17, 17, 17, 255}}
	ReallyRed            = BrickColor{Name: "Really red", Number: 1004, Hex: "#FF0000", RGBA: color.RGBA{255, 0, 0, 255}}
	DeepOrange           = BrickColor{Name: "Deep orange", Number: 1005, Hex: "#FFB000", RGBA: color.RGBA{255, 176, 0, 255}}
	Alder                = BrickColor{Name: "Alder", Number: 1006, Hex: "#B480FF", RGBA: color.RGBA{180, 128, 255, 255}}
	DustyRose            = BrickColor{Name: "Dusty Rose", Number: 1007, Hex: "#A34B4B", RGBA: color.RGBA{163, 75, 75, 255}}
	Olive                = BrickColor{Name: "Olive", Number: 1008, Hex: "#C1BE42", RGBA: color.RGBA{193, 190, 66, 255}}
	NewYeller            = BrickColor{Name: "New Yeller", Number: 1009, Hex: "#FFFF00", RGBA: color.RGBA{255, 255, 0, 255}}
	ReallyBlue           = BrickColor{Name: "Really blue", Number: 1010, Hex: "#0000FF", RGBA: color.RGBA{0, 0, 255, 255}}
	NavyBlue             = BrickColor{Name: "Navy blue", Number: 1011, Hex: "#002060", RGBA: color.RGBA{0, 32, 96, 255}}
	DeepBlue             = BrickColor{Name: "Deep blue", Number: 1012, Hex: "#2154B9", RGBA: color.RGBA{33, 84, 185, 255}}
	Cyan                 = BrickColor{Name: "Cyan", Number: 1013, Hex: "#04AFEC", RGBA: color.RGBA{4, 175, 236, 255}}
	CGABrown             = BrickColor{Name: "CGA brown", Number: 1014, Hex: "#AA5500", RGBA: color.RGBA{170, 85, 0, 255}}
	Magenta              = BrickColor{Name: "Magenta", Number: 1015, Hex: "#AA00AA", RGBA: color.RGBA{170, 0, 170, 255}}
	Pink                 = BrickColor{Name: "Pink", Number: 1016, Hex: "#FF66CC", RGBA: color.RGBA{255, 102, 204, 255}}
	DeepOrange2          = BrickColor{Name: "Deep orange", Number: 1017, Hex: "#FFAF00", RGBA: color.RGBA{255, 175, 0, 255}}
	Teal                 = BrickColor{Name: "Teal", Number: 1018, Hex: "#12EED4", RGBA: color.RGBA{18, 238, 212, 255}}
	Toothpaste           = BrickColor{Name: "Toothpaste", Number: 1019, Hex: "#00FFFF", RGBA: color.RGBA{0, 255, 255, 255}}
	LimeGreen            = BrickColor{Name: "Lime green", Number: 1020, Hex: "#00FF00", RGBA: color.RGBA{0, 255, 0, 255}}
	Camo                 = BrickColor{Name: "Camo", Number: 1021, Hex: "#3A7D15", RGBA: color.RGBA{58, 125, 21, 255}}
	Grime                = BrickColor{Name: "Grime", Number: 1022, Hex: "#7F8E64", RGBA: color.RGBA{127, 142, 100, 255}}
	Lavender             = BrickColor{Name: "Lavender", Number: 1023, Hex: "#8C5B9F", RGBA: color.RGBA{140, 91, 159, 255}}
	PastelLightBlue      = BrickColor{Name: "Pastel light blue", Number: 1024, Hex: "#AFDDFF", RGBA: color.RGBA{175, 221, 255, 255}}
	PastelOrange         = BrickColor{Name: "Pastel orange", Number: 1025, Hex: "#FFC9C9", RGBA: color.RGBA{255, 201, 201, 255}}
	PastelViolet         = BrickColor{Name: "Pastel violet", Number: 1026, Hex: "#B1A7FF", RGBA: color.RGBA{177, 167, 255, 255}}
	PastelBlueGreen      = BrickColor{Name: "Pastel blue-green", Number: 1027, Hex: "#9FF3E9", RGBA: color.RGBA{159, 243, 233, 255}}
	PastelGreen          = BrickColor{Name: "Pastel green", Number: 1028, Hex: "#CCFFCC", RGBA: color.RGBA{204, 255, 204, 255}}
	PastelYellow         = BrickColor{Name: "Pastel yellow", Number: 1029, Hex: "#FFFFCC", RGBA: color.RGBA{255, 255, 204, 255}}
	PastelBrown          = BrickColor{Name: "Pastel brown", Number: 1030, Hex: "#FFCC99", RGBA: color.RGBA{255, 204, 153, 255}}
	RoyalPurple          = BrickColor{Name: "Royal purple", Number: 1031, Hex: "#6225D1", RGBA: color.RGBA{98, 37, 209, 255}}
	HotPink              = BrickColor{Name: "Hot pink", Number: 1032, Hex: "#FF00BF", RGBA: color.RGBA{255, 0, 191, 255}}
)

// All available BrickColors on Roblox.
var All = []BrickColor{
	White,
	Grey,
	LightYellow,
	BrickYellow,
	LightGreenMint,
	LightReddishViolet,
	PastelBlue,
	LightOrangeBrown,
	Nougat,
	BrightRed,
	MedReddishViolet,
	BrightBlue,
	BrightYellow,
	EarthOrange,
	Black,
	DarkGrey,
	DarkGreen,
	MediumGreen,
	LigYellowichOrange,
	BrightGreen,
	DarkOrange,
	LightBluishViolet,
	Transparent,
	TrRed,
	TrLgBlue,
	TrBlue,
	TrYellow,
	LightBlue,
	TrFluReddishOrange,
	TrGreen,
	TrFluGreen,
	PhosphWhite,
	LightRed,
	MediumRed,
	MediumBlue,
	LightGrey,
	BrightViolet,
	BrYellowishOrange,
	BrightOrange,
	BrightBluishGreen,
	EarthYellow,
	BrightBluishViolet,
	TrBrown,
	MediumBluishViolet,
	TrMediReddishViolet,
	MedYellowishGreen,
	MedBluishGreen,
	LightBluishGreen,
	BrYellowishGreen,
	LigYellowishGreen,
	MedYellowishOrange,
	BrReddishOrange,
	BrightReddishViolet,
	LightOrange,
	TrBrightBluishViolet,
	Gold,
	DarkNougat,
	Silver,
	NeonOrange,
	NeonGreen,
	SandBlue,
	SandViolet,
	MediumOrange,
	SandYellow,
	EarthBlue,
	EarthGreen,
	TrFluBlue,
	SandBlueMetallic,
	SandVioletMetallic,
	SandYellowMetallic,
	DarkGreyMetallic,
	BlackMetallic,
	LightGreyMetallic,
	SandGreen,
	SandRed,
	DarkRed,
	TrFluYellow,
	TrFluRed,
	GunMetallic,
	RedFlipFlop,
	YellowFlipFlop,
	SilverFlipFlop,
	Curry,
	FireYellow,
	FlameYellowishOrange,
	ReddishBrown,
	FlameReddishOrange,
	MediumStoneGrey,
	RoyalBlue,
	DarkRoyalBlue,
	BrightReddishLilac,
	DarkStoneGrey,
	LemonMetalic,
	LightStoneGrey,
	DarkCurry,
	FadedGreen,
	Turquoise,
	LightRoyalBlue,
	MediumRoyalBlue,
	Rust,
	Brown,
	ReddishLilac,
	Lilac,
	LightLilac,
	BrightPurple,
	LightPurple,
	LightPink,
	LightBrickYellow,
	WarmYellowishOrange,
	CoolYellow,
	DoveBlue,
	MediumLilac,
	SlimeGreen,
	SmokyGrey,
	DarkBlue,
	ParsleyGreen,
	SteelBlue,
	StormBlue,
	Lapis,
	DarkIndigo,
	SeaGreen,
	Shamrock,
	Fossil,
	Mulberry,
	ForestGreen,
	CadetBlue,
	ElectricBlue,
	Eggplant,
	Moss,
	Artichoke,
	SageGreen,
	GhostGrey,
	Lilac2,
	Plum,
	Olivine,
	LaurelGreen,
	QuillGrey,
	Crimson,
	Mint,
	BabyBlue,
	CarnationPink,
	Persimmon,
	Maroon,
	Gold2,
	DaisyOrange,
	Pearl,
	Fog,
	Salmon,
	TerraCotta,
	Cocoa,
	Wheat,
	Buttermilk,
	Mauve,
	Sunrise,
	Tawny,
	Rust2,
	Cashmere,
	Khaki,
	LilyWhite,
	Seashell,
	Burgundy,
	Cork,
	Burlap,
	Beige,
	Oyster,
	PineCone,
	FawnBrown,
	HurricaneGrey,
	CloudyGrey,
	Linen,
	Copper,
	DirtBrown,
	Bronze,
	Flint,
	DarkTaupe,
	BurntSienna,
	InstitutionalWhite,
	MidGray,
	ReallyBlack,
	ReallyRed,
	DeepOrange,
	Alder,
	DustyRose,
	Olive,
	NewYeller,
	ReallyBlue,
	NavyBlue,
	DeepBlue,
	Cyan,
	CGABrown,
	Magenta,
	Pink,
	DeepOrange2,
	Teal,
	Toothpaste,
	LimeGreen,
	Camo,
	Grime,
	Lavender,
	PastelLightBlue,
	PastelOrange,
	PastelViolet,
	PastelBlueGreen,
	PastelGreen,
	PastelYellow,
	PastelBrown,
	RoyalPurple,
	HotPink}

var byNumber = map[int]BrickColor{
	1:    White,
	2:    Grey,
	3:    LightYellow,
	5:    BrickYellow,
	6:    LightGreenMint,
	9:    LightReddishViolet,
	11:   PastelBlue,
	12:   LightOrangeBrown,
	18:   Nougat,
	21:   BrightRed,
	22:   MedReddishViolet,
	23:   BrightBlue,
	24:   BrightYellow,
	25:   EarthOrange,
	26:   Black,
	27:   DarkGrey,
	28:   DarkGreen,
	29:   MediumGreen,
	36:   LigYellowichOrange,
	37:   BrightGreen,
	38:   DarkOrange,
	39:   LightBluishViolet,
	40:   Transparent,
	41:   TrRed,
	42:   TrLgBlue,
	43:   TrBlue,
	44:   TrYellow,
	45:   LightBlue,
	47:   TrFluReddishOrange,
	48:   TrGreen,
	49:   TrFluGreen,
	50:   PhosphWhite,
	100:  LightRed,
	101:  MediumRed,
	102:  MediumBlue,
	103:  LightGrey,
	104:  BrightViolet,
	105:  BrYellowishOrange,
	106:  BrightOrange,
	107:  BrightBluishGreen,
	108:  EarthYellow,
	110:  BrightBluishViolet,
	111:  TrBrown,
	112:  MediumBluishViolet,
	113:  TrMediReddishViolet,
	115:  MedYellowishGreen,
	116:  MedBluishGreen,
	118:  LightBluishGreen,
	119:  BrYellowishGreen,
	120:  LigYellowishGreen,
	121:  MedYellowishOrange,
	123:  BrReddishOrange,
	124:  BrightReddishViolet,
	125:  LightOrange,
	126:  TrBrightBluishViolet,
	127:  Gold,
	128:  DarkNougat,
	131:  Silver,
	133:  NeonOrange,
	134:  NeonGreen,
	135:  SandBlue,
	136:  SandViolet,
	137:  MediumOrange,
	138:  SandYellow,
	140:  EarthBlue,
	141:  EarthGreen,
	143:  TrFluBlue,
	145:  SandBlueMetallic,
	146:  SandVioletMetallic,
	147:  SandYellowMetallic,
	148:  DarkGreyMetallic,
	149:  BlackMetallic,
	150:  LightGreyMetallic,
	151:  SandGreen,
	153:  SandRed,
	154:  DarkRed,
	157:  TrFluYellow,
	158:  TrFluRed,
	168:  GunMetallic,
	176:  RedFlipFlop,
	178:  YellowFlipFlop,
	179:  SilverFlipFlop,
	180:  Curry,
	190:  FireYellow,
	191:  FlameYellowishOrange,
	192:  ReddishBrown,
	193:  FlameReddishOrange,
	194:  MediumStoneGrey,
	195:  RoyalBlue,
	196:  DarkRoyalBlue,
	198:  BrightReddishLilac,
	199:  DarkStoneGrey,
	200:  LemonMetalic,
	208:  LightStoneGrey,
	209:  DarkCurry,
	210:  FadedGreen,
	211:  Turquoise,
	212:  LightRoyalBlue,
	213:  MediumRoyalBlue,
	216:  Rust,
	217:  Brown,
	218:  ReddishLilac,
	219:  Lilac,
	220:  LightLilac,
	221:  BrightPurple,
	222:  LightPurple,
	223:  LightPink,
	224:  LightBrickYellow,
	225:  WarmYellowishOrange,
	226:  CoolYellow,
	232:  DoveBlue,
	268:  MediumLilac,
	301:  SlimeGreen,
	302:  SmokyGrey,
	303:  DarkBlue,
	304:  ParsleyGreen,
	305:  SteelBlue,
	306:  StormBlue,
	307:  Lapis,
	308:  DarkIndigo,
	309:  SeaGreen,
	310:  Shamrock,
	311:  Fossil,
	312:  Mulberry,
	313:  ForestGreen,
	314:  CadetBlue,
	315:  ElectricBlue,
	316:  Eggplant,
	317:  Moss,
	318:  Artichoke,
	319:  SageGreen,
	320:  GhostGrey,
	321:  Lilac2,
	322:  Plum,
	323:  Olivine,
	324:  LaurelGreen,
	325:  QuillGrey,
	327:  Crimson,
	328:  Mint,
	329:  BabyBlue,
	330:  CarnationPink,
	331:  Persimmon,
	332:  Maroon,
	333:  Gold2,
	334:  DaisyOrange,
	335:  Pearl,
	336:  Fog,
	337:  Salmon,
	338:  TerraCotta,
	339:  Cocoa,
	340:  Wheat,
	341:  Buttermilk,
	342:  Mauve,
	343:  Sunrise,
	344:  Tawny,
	345:  Rust2,
	346:  Cashmere,
	347:  Khaki,
	348:  LilyWhite,
	349:  Seashell,
	350:  Burgundy,
	351:  Cork,
	352:  Burlap,
	353:  Beige,
	354:  Oyster,
	355:  PineCone,
	356:  FawnBrown,
	357:  HurricaneGrey,
	358:  CloudyGrey,
	359:  Linen,
	360:  Copper,
	361:  DirtBrown,
	362:  Bronze,
	363:  Flint,
	364:  DarkTaupe,
	365:  BurntSienna,
	1001: InstitutionalWhite,
	1002: MidGray,
	1003: ReallyBlack,
	1004: ReallyRed,
	1005: DeepOrange,
	1006: Alder,
	1007: DustyRose,
	1008: Olive,
	1009: NewYeller,
	1010: ReallyBlue,
	1011: NavyBlue,
	1012: DeepBlue,
	1013: Cyan,
	1014: CGABrown,
	1015: Magenta,
	1016: Pink,
	1017: DeepOrange2,
	1018: Teal,
	1019: Toothpaste,
	1020: LimeGreen,
	1021: Camo,
	1022: Grime,
	1023: Lavender,
	1024: PastelLightBlue,
	1025: PastelOrange,
	1026: PastelViolet,
	1027: PastelBlueGreen,
	1028: PastelGreen,
	1029: PastelYellow,
	1030: PastelBrown,
	1031: RoyalPurple,
	1032: HotPink,
}
